### ISSUE TITLE
New version in sight?

### ISSUE THREAD

**Issue by rept** [turbolinks/turbolinks-android#108]
Any news about the new version?  Could the new TrustedWebActivity from Google offer a solution here?

**Comment by jayohms** [comment]
I'm actively working on the Turbolinks library, now. I don't have a timeframe to share, because I don't have a good estimate at the moment. The new library will use a single-activity architecture  and it leverages [Google's Navigation Component](https://developer.android.com/guide/navigation/navigation-getting-started). I'll share more once we're close to completion.

`TrustedWebActivity` is not a good fit for Turbolinks, since we need native <-> web communication with the `WebView`. This is [expressly prohibited](https://blog.chromium.org/2019/02/introducing-trusted-web-activity-for.html) in `TrustedWebActivity`:

> The content of a TWA is protected and cannot be read or modified by the enclosing application. That means state can only be shared from the app to the TWA when it is initialized by passing in query string parameters and it is not possible to insert content into the TWA from the Android application.

**Comment by phil-monroe** [comment]
@jayohms - Thanks for you work and I am excited to see that progress is being made. We are using a modified version of turbolinks-android using fragments and a single activity here at Maven (sellwithami.com). We are happy to help test or perhaps contribute if you need any help!

**Comment by rept** [comment]
@jayohms thanks for the feedback.
