### ISSUE TITLE
Update on Turbolinks v2

### ISSUE THREAD

**Issue by pinzonjulian** [turbolinks/turbolinks-android#111]
Hi, I was just wondering if anyone knew anything on updates on TL v2? Super exited to use it on new projects!

**Comment by henrik** [comment]
I don't work for Basecamp and don't have any insight into their progress, but there's a "still in development" update here from July 3: https://github.com/turbolinks/turbolinks-android/issues/110#issuecomment-508091299

**Comment by szTheory** [comment]
It's not a complete replacement but apparently the Google Play Store allows PWA submissions. So even if turbolinks-android v2 never came, there would be some recourse to get your app submitted for Android.

**Comment by henrik** [comment]
Basecamp owes us nothing, but for whatever it's worth, we're making some business decisions soon that would be helped by a rough-as-you-like, no-promises update on this as well.

**Comment by svantepolk** [comment]
Basecamp is busy working on a new product at the moment, so we're going to have to be patient.

**Comment by jayohms** [comment]
I'm sorry for the radio silence recently. As @svantepolk mentioned, yes we are indeed actively working on a new product. In tandem with that product, I'm developing the new turbolinks-android library leveraging Google's new(er) [Navigation Component framework](https://developer.android.com/guide/navigation/navigation-getting-started). The new turbolinks-android library will be based on a single-Activity architecture which completely avoids the trouble we ran into before deprecating the older version.

I wish we were closer to open sourcing the new version, but the APIs are still changing on a daily or weekly basis, since the new library takes a much larger role in transparently handling complex navigation flows, remote configurations, and session management. My goal is have an early version public sometime before RailsConf in May. I don't have a more exact timeline than that, but we are working hard on the next version of Turbolinks and the mobile libraries.

**Comment by tlvenn** [comment]
Hi @jayohms , is there any update on your side ? Thanks in advance.

**Comment by henrik** [comment]
@tlvenn I don't work for Basecamp, but the new product (assuming we're talking about hey.com) [has been delayed due to guess-what](https://m.signalvnoise.com/why-hey-had-to-wait/), so that seems likely to affect this too.

**Comment by tlvenn** [comment]
Yes I guessed as much but was wondering if it reached a more mature state given they were initially targeting a release around now or more broadly was merely curious how things were shaping up.

**Comment by pinzonjulian** [comment]
Thanks for the update @jayohms ! No need to apologise for the delays :). It's very useful for us to have this mini updates to be able to plan the development of our own apps and make the best decisions possible for our projects.
Can't wait to see the new release. Thanks!

**Comment by jankeesvw** [comment]
@jayohms we are about to start on an Android version of our iOS with Turbolinks. Is it wise to wait until the new Android library is released, or is the implementation side mostly the same? We don't have a massive deadline..

**Comment by jayohms** [comment]
@jankeesvw If you don't have a massive deadline, then it would make sense to wait. The implementations are substantially different - the main one being that the new library will rely on a single-`Activity` app architecture, which is the main reason we had to deprecate the original library. You'll also no longer will need to manually manage the `TurbolinksSession` and the `Activity` lifecycle events - the new library takes care of all of that.

That being said, I understand that it's probably frustrating to not have anything to work with yet. The good news is that the new Turbolinks library in HEY has proven to be very stable in production so far - outside of a few minor bugs that we've had to address. The HEY launch has been a wild ride and we're still catching our breath a bit, but soon we should be able to focus on open sourcing the various libraries and components in the stack across all platforms.

[https://twitter.com/dhh/status/1275902966197743619](https://twitter.com/dhh/status/1275902966197743619)

**Comment by Bramjetten** [comment]
Sorry for being pushy, but are we talking weeks or months here? 😅

**Comment by basicBrogrammer** [comment]
@jayohms Any reason not to make the push to v2 open source? The deprecation was one reason i started rebuilding a side project with ionic. I would have loved spend my time contributing to pushing this project forward. Did yall just wanna lay the new ground work bc it was a rewrite or something ?

**Comment by JoseFarias** [comment]
Seeing that other similar issues have been opened in sister repos (see turbolinks/turbolinks#576 and turbolinks/turbolinks-ios#173) there seems to be community interest in knowing the following:

- Is there a shareable roadmap or release plan for `turbolinks`, `turbolinks-ios` and `turbolinks-android`? Ideally including approximate dates.
- Is there a plan for Basecamp to actively and officially maintain the new versions of these libraries into the future?

More info on my situation might help:
We want to use turbolinks for v2 of our startup's apps but haven't been able to, primarily because we don't want to start building for Android knowing that a re-engineered version of turbolinks might be just around the corner. We're finishing up on a startup accelerator program, so having a clear roadmap for our product would help us potentially secure funding.

I know Basecamp has been super busy lately and they don't owe us anything. But having the above info would be very helpful in planning for new and existing projects.

It would be very much appreciated if Basecamp is able to make the time to communicate this info. Thanks for all the amazing work you've put out into the community!

**Comment by anatoliyarkhipov** [comment]
@JoseFarias No offense, just FYI and maybe other readers - Basecamp deliberately avoids roadmaps, so what you're asking for likely doesn't exist, and it's not a matter of finding time to share it (an article about it, if you're interested - https://m.signalvnoise.com/options-not-roadmaps/).

**Comment by JoseFarias** [comment]
@anatoliyarkhipov gotcha, this makes sense. I feel silly because I actually did know about that philosophy. Seems like I forgot.

I guess what I'm hoping is that if the team was flexible enough on their roadmap policies to give approximate dates in past comments, they might be flexible enough to provide more accurate estimates today. Completely understandable if they don't want to, it's just that a guy's gotta ask 😁.

**Comment by Bramjetten** [comment]
@anatoliyarkhipov Rails is very actively maintained and not dependent on Basecamp. I'd like that for Turbolinks as well (specifically for iOS and Android). 

I am very happy these adapters exist. It allows me as a solo developer to create fully fledged apps without having to learn a lot about iOS & Android development. However, it's been almost two years since the Android adapter was deprecated and the Basecamp team has been hinting at an entirely new way of creating apps with Turbolinks. I'm sure it's going to be great, but I've been postponing new versions for our Android apps for quite some time now. 

If this is how it's going to be in the future, I have to invest in learning something else to create hybrid apps. I'd prefer to keep using Turbolinks though, because – aside from Android – I really love building apps with it!

**Comment by JoseFarias** [comment]
@Bramjetten I would love to see more community involvement in these adapters as well. I'm just not sure how to achieve it given that every time I've thought about this I get discouraged because the audience for these libraries is simply much, much smaller than the audience for Rails. Plus, I don't have any experience working on open source software.

This is a bit off-topic though. So in the meantime I'll just ask anyone who feels this way (and maybe has more experience in open source) to contact me so we can find a way to make it happen.

**Comment by tleish** [comment]
See:
https://twitter.com/dhh/status/1291114354482524160
and
https://twitter.com/dhh/status/1292784841444986880

**Comment by basicBrogrammer** [comment]
The suspense 

https://media.giphy.com/media/brHaCdJqCXijm/giphy.gif

**Comment by svantepolk** [comment]
**How it started**
<img width="862" alt="Screen Shot 2020-11-12 at 12 57 06 pm" src="https://user-images.githubusercontent.com/25386350/98889933-9c66e880-24e6-11eb-91b9-fc9c992f86b0.png">

**How it's going**
![3](https://user-images.githubusercontent.com/25386350/98889955-abe63180-24e6-11eb-8d5b-949f535d02cb.jpg)

**Comment by lateplate** [comment]
Really appreciate y'all sticking with us, and sorry for the lack of updates. Your patience (and good humor) on the matter is really appreciated.

Things are stabilizing with the nav framework from Google, so things are looking good. I can't really give a timeline because there are a few things we have to coordinate as it relates to core Turbolinks. I can tell you that the library is in good shape (good enough to run [HEY](https://hey.com)) since launch. We are right now doing an early pass on documentation so that when we do release, y'all will have something to work with, because it's significantly more complex than v1 of the library.

We were really hoping for a 2020 release, but given it's November, that seems highly unlikely to me. I wish I could give you a timeframe, but I feel like I would just be speculating, especially given that we've missed a couple targets already. But to be fair, 2020 has not exactly gone as planned 😬

Again, thank you for your patience and understanding, and please keep making jokes because they're helping. 😆

As soon as we know more, we'll update.

**Comment by Bramjetten** [comment]
@lateplate Thanks for the status update, it’s much appreciated. Please consider sharing anything you have before documentation is done, that could help us a lot! (I promise not to spam you with questions 🤫)

**Comment by silva96** [comment]
🆕  🎩  plz

**Comment by jayohms** [comment]
We've made a lot of progress and will have a public (alpha) release very soon, probably in the next couple weeks.

Thanks for bearing with us ❤️ . Stay tuned 😀

**Comment by brusacco** [comment]
Waiting for the public alpha to test it. Thanks!

**Comment by jayohms** [comment]
The new Turbo framework for Android is now available 🎉 . We've also pushed out tons of new magic today. See it all at https://hotwire.dev

New repo: https://github.com/hotwired/turbo-android
Other repos: https://github.com/hotwired

Thanks for all your patience and we'd love to hear your feedback! I'll be closing issues/comments on this repo soon, since it will no longer be used.

**Comment by henrik** [comment]
Sneaking in a congrats on shipping before you turn off comments 🥳

**Comment by zbaloch** [comment]
Literally been holding onto start my Android app for this. Thank you so much @jayohms

**Comment by svantepolk** [comment]
The demo and documentation is very compelling and this looks like it's easily exceeded all of my hopes and expectations. Can't wait to put it to use!

Thanks for making this happen (and in time for the new year, no less!)

**Comment by pinzonjulian** [comment]
Thank you very much @jayohms and all the team at Basecamp! 

I'll now happily close this issue. 

Let's start hotwiring! ⚡️

> The new Turbo framework for Android is now available 🎉 . We've also pushed out tons of new magic today. See it all at https://hotwire.dev
> 
> New repo: https://github.com/hotwired/turbo-android
> Other repos: https://github.com/hotwired
> 
> Thanks for all your patience and we'd love to hear your feedback! I'll be closing issues/comments on this repo soon, since it will no longer be used.

**Comment by silva96** [comment]
👏  👏  👏  👏  thanks!!!
