### ISSUE TITLE
SSL and self signed certs

### ISSUE THREAD

**Issue by digimedia** [turbolinks/turbolinks-android#17]
I'm using a self signed cert on aws beanstalk for development. Is there a way for TurbolinksSession to handle this?

**Comment by lateplate** [comment]
I'm not sure what the scenario you're describing is/how it relates to Turbolinks. Could you provide more detail?

Turbolinks doesn't specifically prefer any SSL mechanisms, as it relies on the Android webview to handle all of that. If you're running into a specific issue though, let us know.

**Comment by KellyMahan** [comment]
Sorry signed into companies github account when I posted. 

I'm a rails developer and unfamiliar with android development. I used the demo code and was able to load the page until I used an https url. I know with android it will error out unless a valid trusted cert is used. I have a valid self signed cert but it isn't trusted.

**Comment by KellyMahan** [comment]
take a look at my ignoressl branch from the forked repository

+            public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
+                handler.proceed(); // Ignore SSL certificate errors
+            }

you wouldn't want to ignore all ssl errors, but that corrects my issue for a self signed cert.

**Comment by lateplate** [comment]
Hi @KellyMahan, sorry for the delay on this one.

I personally haven't run into what you hit (haven't had to hit an SSL connection w/o a signed cert), but I can see how that could happen.

I think what you have in your fork is fine as a workaround, but for production use, I think we'd want to to pass the callback up to the `TurbolinksAdapter` class, then let the caller handle it however they want. That would provide the greatest flexibility instead of just allowing a cert warning from passing all the time.

If you'd like to take a stab at that, that'd be great! If not, no worries. Let me know!
