### ISSUE TITLE
WebView state is not saved/restored breaking rotation

### ISSUE THREAD

**Issue by candrews** [turbolinks/turbolinks-android#28]
The WebView's state isn't saved in the bundle so it is lost when the activity hosting it is suspended (such as due a configuration change like device rotation).

`TurbolinksView` should implement the save and restore instance methods, something like this:
```java
@Override
protected Parcelable onSaveInstanceState() {
	// Create a bundle to put super parcelable in
	Bundle bundle = new Bundle();
	bundle.putParcelable("super", super.onSaveInstanceState());
	webView.saveState(bundle);
	return bundle;
}

@Override
protected void onRestoreInstanceState(Parcelable state) {
	Bundle bundle = (Bundle) state;
	webView.restoreState(bundle);
	super.onRestoreInstanceState(bundle.getParcelable("super"));
}
```

I'm just not sure how to get the `webView` in order to submit a PR.

**Comment by jayohms** [comment]
@candrews We've found for most activities we don't need to save specific activity instance state for device rotation, since the majority of the UI is the `WebView` and its state is managed by Turbolinks (and swapping native resources are not necessary). We have the following on our `<activity>` declarations in our manifest to avoid automatic activity restarts for orientation or screen size changes:

```
android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
```
https://developer.android.com/guide/topics/resources/runtime-changes.html#HandlingTheChange

The library doesn't not manage the activity lifecycle, and I don't see us changing that anytime soon. If, however you'd like to manage the activity lifecycle and instance state, you can easily obtain a reference to the webview in your activity from:
```
TurbolinksSession.getDefault().getWebView()
```

With the `WebView` reference, you can save any instance state you'd like.

**Comment by candrews** [comment]
I agree that having the Activity use `TurbolinksSession.getDefault().getWebView()` to save/restore state is a good workaround and I'm doing that today - but, it does seem surprising that `TurbolinksView` doesn't save/restore state because other views do. For example, if I simply put a `WebView` in my layout, it would automatically have it's state saved/restored, but changing that `WebView` to a `TurbolinksView` doesn't.

**Comment by jayohms** [comment]
@candrews I agree that it would probably be beneficial as a default. Curious, do you have other instance state that you're managing for native UI?

We're going to cut a new version of the library soon. Currently, there's not a direct way to access the `WebView` in `TurbolinksView`. If there's a straightforward way of doing that without it turning into a leaky reference, we can save the instance state easily like you mentioned.

**Comment by candrews** [comment]
I do not currently have any other instance state that I'm managing for the native UI.

I feel like there has to be away to do this... `TurbolinksView` has a reference to `TurbolinksSession` and that has the `WebView` so can it be retrieved using that chain?

**Comment by lateplate** [comment]
@candrews If you have a code suggestion, we'd be happy to look at it via a pull request. That's often the best way to move along an issue you feel strongly about. Thanks!

**Comment by jayohms** [comment]
@candrews Version 1.0.3 has just been released. Note that the `WebView` can now be obtained internally in `TurbolinksView` via:
```
refreshLayout..getChildAt(1)
```
A test has also been added for this: 
https://github.com/turbolinks/turbolinks-android/blob/master/turbolinks/src/test/java/com/basecamp/turbolinks/TurbolinksViewTest.java#L38
