### ISSUE TITLE
Stripe.js CORS error

### ISSUE THREAD

**Issue by leequarella** [turbolinks/turbolinks-android#41]
Have stripe integrated in an app, everything working nicely in web and iOS (well, still a kink to work out with the form submitting as post back to the webserver in the turbolinks-[native] app, but that shouldn't be much of a hassle to get going. 

This script gives us the button to trigger a call out to stripe.

``` ruby
  = form_for @stripe_card, html: { role: "form", id: "stripe_card_form" } do |f|
  %script{src: "https://checkout.stripe.com/checkout.js",
    class: "stripe-button",
    "data-key"   => ENV["stripe_publishable_key"],
    "data-name"  => "Add Payment Method",
    "data-label" => "Add Card",
    "data-email" => current_user.email,
    "data-panel-label" => "Save"}
```

Everything works fine in the turbolinks-ios app, but android gives this in the logs (this is from local, but also fails from FQDN):

> 08-30 09:36:14.982 14595-14595/com.xxx.xxx I/chromium: [INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://checkout.stripe.com/v3/BFV9gQSjIO6MQNzvbBr9GA.html?distinct_id=6a50565d-2992-82c7-6bfb-5b4091061faf. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.5.102:3000' is therefore not allowed access. The response had HTTP status code 405.", source: http://192.168.5.102:3000/users/1 (0)
> 
> 08-30 09:36:14.982 14595-15189/com.xxx.xxx D/TurbolinksLog: visitRequestFailedWithStatusCode called

I tried with this in onCreate:

``` java
  WebSettings settings = TurbolinksSession.getDefault(this).getWebView().getSettings();
  settings.setAllowContentAccess(true);
  settings.setAllowFileAccessFromFileURLs(true);
  settings.setAllowUniversalAccessFromFileURLs(true);
  settings.setAllowFileAccess(true);
```

No luck there... where have I gone wrong?

**Comment by leequarella** [comment]
Some info from #stripe IRC:

>leequarella: ahh, it seems that something is trying to load Checkout over ajax - Checkout must be loaded by embedding a script tag in the page's HTML and letting the browser/webview fetch and render it

Should I be forcing turbolinks to ignore that traffic somehow so the webview does its normal thing?

**Comment by seanlinsley** [comment]
I get a similar error when attempting OAuth login (Facebook, Google, Twitter)

**Comment by seanlinsley** [comment]
When setting `data-turbolinks="false"`, Turbolinks JS doesn't handle the link but the Android app still does. Even when doing this:
```coffee
Turbolinks.controller.nodeIsVisitable = (node)->
  false
```

I still get this in the Android logs:
```
D/TurbolinksLog: Overriding load: [snip]
D/TurbolinksLog: visitProposedToLocationWithAction called

...

I/chromium: [INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://www.facebook.com/v2.2/dialog/oauth?client_id=[snip]&display=popup&redirect_uri=[snip]%2Fcallback&response_type=code&state=[snip]. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '[snip]' is therefore not allowed access.", source: [snip] (0)
```

**Comment by seanlinsley** [comment]
This function seems to be the culprit:
```java
/**
 * Turbolinks will not call adapter.visitProposedToLocationWithAction in some cases,
 * like target=_blank or when the domain doesn't match. We still route those here.
 * This is mainly only called when links within a webView are clicked and not during
 * loadUrl. However, a redirect on a cold boot can also cause this to fire, so don't
 * override in that situation, since Turbolinks is not yet ready.
 * http://stackoverflow.com/a/6739042/3280911
 */
@Override
public boolean shouldOverrideUrlLoading(WebView view, String location) {
    if (!turbolinksIsReady || coldBootInProgress) {
        return false;
    }

    /**
     * Prevents firing twice in a row within a few milliseconds of each other, which
     * happens. So we check for a slight delay between requests, which is plenty of time
     * to allow for a user to click the same link again.
     */
    long currentOverrideTime = new Date().getTime();
    if ((currentOverrideTime - previousOverrideTime) > 500) {
        previousOverrideTime = currentOverrideTime;
        TurbolinksLog.d("Overriding load: " + location);
        visitProposedToLocationWithAction(location, ACTION_ADVANCE);
    }

    return true;
}
```

It calls `visitProposedToLocationWithAction`, which ends up calling the JS:

```js
webView.visitLocationWithActionAndRestorationIdentifier('http://your/link', 'advance')
```

which calls `startVisitToLocationWithAction` on `Turbolinks.controller`:
```coffee
  startVisitToLocationWithAction: (location, action, restorationIdentifier) ->
    if Turbolinks.supported
      restorationData = @getRestorationDataForIdentifier(restorationIdentifier)
      @startVisit(location, action, {restorationData})
    else
      window.location = location
```

The problem is, unlike `visit` right above it, this function doesn't check `locationIsVisitable`.

The result is that Turbolinks handles the link click even if you don't want it to.

It's hard to divine the intention between e.g. `visit` versus `startVisitToLocationWithAction`, so I'm not sure what the correct solution here is. But it does seem like the JS should be updated, or at least the Android code should call a different JS function (as opposed to copying some form of `data-turbolinks="false"` into the Android code)

@lateplate @jayohms any ideas?

**Comment by lateplate** [comment]
Hey all -- thanks all for all your investigation, and sorry for the delay. I'm hoping I can take a look at this one in the next few weeks. 

I suspect `shouldOverrideUrlLoading` in the WebViewClient is the issue (which would explain why the other platforms aren't having issues). 

This piece of code was tricky because:

1. It's the worst part/least predictable part of webview. I had tons of trouble with it (note the hack with the double firing in the comments)
1. The most deeply embedded to a lot of click-interception scenarios. I had to test a lot of random scenarios, an I'm sure some were missed, maybe badly.

So I'll need some more time to unwind this. Any investigation you can offer is certainly greatly appreciated. 

Thanks.

**Comment by jean-francois-labbe** [comment]
I've got this issue, any idea how to fix this?

**Comment by md-hamed** [comment]
@lateplate Is there any plans to resolve this in near future?
