### ISSUE TITLE
Pull to refresh refreshed wrong url

### ISSUE THREAD

**Issue by deeankmet** [turbolinks/turbolinks-android#52]
I'm having problems with implementing onBackPressed for my application.
If I use this,

``` java
   private boolean visitBack(){
        if (mySession.getWebView().canGoBack()) {
            mySession.getWebView().goBack();
            return true;
        }else{
            return false;
        }
    }
```

My webview will properly go back to the previous url, but when I pull to refresh it, it will go back to to the url I just went back from.

But if I use something like this,

``` java
   private boolean visitBack(){
        if (mySession.getWebView().canGoBack()) {
            WebBackForwardList mWebBackForwardList = mySession.getWebView().copyBackForwardList();
            String historyUrl = mWebBackForwardList.getItemAtIndex(mWebBackForwardList.getCurrentIndex()-1).getUrl();
            mySession
                    .activity(this)
                    .adapter(this)
                    .restoreWithCachedSnapshot(true)
                    .view(turbolinksView)
                    .visit(historyUrl);
            return true;
        }else{
            return false;
        }
    }
```

The pull to refresh will refresh the correct page, but my scroll-position in the webview will be lost. 
Is there any way to solve this? 
When I used goBack in my webview, is there any way to tell TurboLinks that the url has been changed?

**Comment by lateplate** [comment]
Generally you shouldn't interact with a Turbolinks webview's back methods directly. Your second code snippet (using a visit with the historical URL) is the correct way.

As far as why scroll position is being lost -- was your initial webview load fired through Turbolinks? If you loaded a URL manually through the webview, then Turbolinks would have no cache snapshot to refer to. Otherwise, a restoration visit _should_ get your scroll position, assuming the Turbolinks core is working properly.
