### ISSUE TITLE
Attaching metadata to link clicks via HTML data attributes

### ISSUE THREAD

**Issue by joemasilotti** [turbolinks/turbolinks-android#6]
To continue a [conversation with Dan Kim](https://twitter.com/joemasilotti/status/704366532613312512), I am trying to pass more context when a user clicks a link.

## Summary

To my understanding, when a user clicks a link `visitProposedToLocationWithAction()` is called with the URL and the Turbolinks action. I would like to be able to pass more information along with this method. Let's say, for example, that the method was passed along with the HTML anchor node associated with the link click. Then developers could attach metadata in the form of HTML data attributes.

## Advantages

What does this get us? Mainly one huge feature: keeping more logic on the server. By doing so we can set small flags, such as `data-modal=true` to have the client automatically open those links modally vs. in the navigation stack.

Or, the client could have one generic `FormActivity` with *Submit* and *Save* buttons. When the `data-form=true` flag is set the client knows to present that activity. We don't need to worry about routing each endpoint that needs the form, that is managed on the server. We can add new endpoints on our server that require a form and not need to update the native client.

You could also set `data-screen-title="Page Two"` on an anchor element. Then you could set the title of the next page before the web view even finishes loading! I am using this approach in our hybrid iOS app (that also takes advantage of Turbolinks) and it makes it feel even more "native".

## Potential Workarounds

1. Perhaps there is a better solution to this problem. Is it possible to grab the anchor elements via a JavaScript selector? But what happens when the same URL is used for multiple anchors?
2. I would prefer to *not* use the `#` URL anchor to store this metadata. I first attempted that and as soon as you have more than one attribute the URL becomes very messy and hard to manage.
3. Something else entirely? I'm open to discussion!

**Comment by glennfu** [comment]
I think the data- attributes are the right place for this. Obviously the behavior is very custom and there's lots of room for creativity, but peeking under the hook of Basecamp 3 shows they're using attributes like `data-bridge-alt` to set the title, `data-bridge-action` and `data-bridge-action-type` to do... I don't know, something with buttons. But basically they have tons of `data-bridge-foo` attributes sprinkled through their source to add native hooks. I can imagine a `<a data-bridge-next-title='Page Two'>click me</a>` to follow along with that convention.

Speaking of which, slight hijack: Anyone know when (or if) the code for that bridge is coming to this project? It would be SUPER awesome to have, but I don't actually know if the Basecamp team plans on sharing their implementation of all of that.

I'm in a similar boat as you, Joe, where I had started a hybrid iOS + Turbolinks 3 project, and it was going well. I was starting to hack Turbolinks 3 for better hooks and then I saw that Turbolinks 5 with native wrappers was coming. I rejoiced, then abandoned my project and I've been impatiently awaiting this one ever since :smile:

**Comment by joemasilotti** [comment]
Those are some interesting findings @glennfu! Its nice to know someone else is interested in the `data-` attribute approach.

**Comment by lateplate** [comment]
@joemasilotti I appreciate the idea here. There are a bunch of ways to slice this. If you wanted to spike something out, I'd be happy to review the PR.

But to me passing metadata along with the Turbolinks visit request starts to blur the focus of the library, which is primarily to bridge execution of Turbolinks actions smoothly.

I understand the idea of having more server side logic, but passing it with a Turbolinks visit feels like the wrong place for that. You might be able to accomplish something similar with a server-side manifest file that your app can read in at launch and use for routing and/or presentation logic. That manifest could be shared cross platform and potentially accomplish the same thing.

In the meantime, you could accomplish something similar by implementing the `visitCompleted` in the `TurbolinksAdapter` interface and firing Javascript at that point. I realize this doesn't provide the same server-side logic benefit, but it could get you to where you want to be. 

We are also planning to, at some point, expose more the Turbolinks callbacks into `TurbolinksAdapter`. To start we kept it simple to the things we used most, but eventually we'll want all the Turbolinks callbacks available to you so you can sequence your events however you like.

Again, happy to discuss further or review a PR. Thanks!

**Comment by lateplate** [comment]
> Anyone know when (or if) the code for that bridge is coming to this project? It would be SUPER awesome to have, but I don't actually know if the Basecamp team plans on sharing their implementation of all of that.

@glennfu We don't have any plans to release our bridge right now. Sorry! 

> But basically they have tons of data-bridge-foo attributes sprinkled through their source to add native hooks.

FWIW, these are used by a wide variety of events in BC3, beyond just native hooks.

**Comment by glennfu** [comment]
Oh bummer! I thought that the intention was to give Turbolinks users a "backpack" to build native-like apps without having to become Android/iOS developers. Without that Bridge, it's still a very large canyon to cross.

At the very least, being able to interact with modals and the native title bars and menu icons seems like a must if someone truly wants to use Turbolinks to build native apps.

I was imagining that Bridge being a foundation, and pull requests being submitted for things like, Facebook auth across iOS and Android to hook into your Rails+omniauth social auth hooks. That maybe slightly outside the scope of the original vision of Turbolinks, but absolutely necessary for anyone using Turbolinks-Android and Turbolinks-iOS. Certainly anyone who wants social login and appreciates this project will want a place to collaborate on those "plugins" and I would imagine it would be a lot smoother if this team was structuring the plugin/bridge architecture. 3rd party Turbolinks plugins without the support/guidance of this team would be really strange!

**Comment by joemasilotti** [comment]
Thanks for the insight, @lateplate.

Using the `visitCompleted` callback has a few issues. First, the view has already been presented and the HTML rendered. This does not allow a developer to present the screen modally or use a different activity to wrap the web view in. Second, even if the callback occurred earlier, there is no deterministic way to retrieve the HTML node from the URL alone. There could be multiple anchors that match the URL, among other things.

I am happy to submit a PR, but diving a little deeper it looks like it will need to touch the Turbolinks JS project as well. My thoughts are to have the [clickBubbled](https://github.com/turbolinks/turbolinks/blob/5250b849f7de4eef886620cf557d15652052a62f/src/turbolinks/controller.coffee#L140) method pass along `event.target` to `notifyApplicationBeforeVisitingLocation` and add the node to the `data` parameter.

Once that is in place this project should be able to easily bubble up that as a new parameter to `visitProposedToLocationWithAction()`. Perhaps `visitProposedToLocationWithActionFromNode()` could work.

Do you think this is something the repos would be interested in including? Obviously, I understand this is quite hand-wavy without actual code. So I'm happy to just submit the two PRs.

**Comment by lateplate** [comment]
@glennfu The bridge we use internally doesn't do anything too fancy, so there isn't really anything to release. It'd be pretty straightforward to recreate in your app if you wanted something similar.

On the Rails side, we read various elements and attributes from the DOM, and expose them through a convenience Javascript object we call `Bridge`.

Then using the `TurbolinksSession`'s handle to the WebView, we execute Javascript that we've injected into the page. That Javascript then talks to the `Bridge` object on the page to get the data we need.

So there's really nothing to release. The `Bridge` you build would be specific to your app's needs (and DOM), as would the interface from the Android side.

**Comment by glennfu** [comment]
@lateplate "doesn't do anything too fancy" sounds like you're selling yourself short ;) I've been very impressed, but perhaps the elegance is in the simplicity you describe. However, since I'm the target audience for this project, that means I'm not already a native Android developer! I've dabbled but not being an Android customer, the whole structure confuses me.

Basically, if I want to use `<h2 data-bridge-alt='Stinker Mobile App'>Message Board in Stinker Mobile App</h2>`, like I've seen in the Basecamp source to create a nav bar with title, like so:

![basecamp3natives](https://cloud.githubusercontent.com/assets/20549/13504377/cb8ce3e4-e139-11e5-87e6-66ad4a39de88.png)

I have NO idea how to go about it. Assuming I go learn enough iOS and Android development to do exactly that, it's not clear to me a good way to structure or architect the binding between the HTML and the respective native counterparts. Assuming again I do make a decision and do something that hopefully is a decent decision there, I'm going to feel very thankful for Turbolinks Native for making this possible and will want to share what I've built. Where would you suggest I submit that code? A new project? A pull request here? I'm sure 90% of the users of Turbolinks Native are going to want to be able to create a nav bar with a title and not all of them are going to want to learn iOS and Android development to do it.

My worry is that I'll go through all this trouble, implement, share, etc, and then you'll look at my project and go "eew that's not going to work out" because you've literally implemented that exact feature already for Basecamp 3 and have come up with a proven structure that you know works well for this purpose.

What do you think about maybe at least a Wiki entry showing an example of how to do nav bar + title, and leave the rest as an exercise to the reader? I'm going to need at least that and it would be awesome to have a starting point I can feel confident in for pursuing the rest.

**Comment by joemasilotti** [comment]
I've taken the liberty of giving the PRs a shot. Any feedback would be greatly appreciated!

**Comment by lateplate** [comment]
@glennfu I can appreciate where you're coming from, but what you're describing is beyond the scope of Turbolinks and this native library. The library is intended for Android developers who want to build high fidelity, hybrid apps, so having a working knowledge of Android is a broad prerequisite. Sorry if that wasn't clear.

While we are conceptually bridging native and web elements, it's primarily from a routing, navigational, and performance perspective -- giving you a shared webview that can follow you along and leverage Turbolinks (not require a full cold boot of the page's resources).

I think there's definite value in examples in the wiki or even additions to the demo app. I'd be quite happy if someone would be willing to tackle those.

And please feel free to log specific, targeted issues. That'll help us keep track of individual requests without conflating conversations too much. Thanks!

**Comment by lateplate** [comment]
@joemasilotti I'm going to close this issue in favor of your pull request (https://github.com/turbolinks/turbolinks-android/pull/7). We can discuss further there. Thanks!

**Comment by joemasilotti** [comment]
:+1:
