### ISSUE TITLE
Pull to refresh breaks scrolling in flexbox elements

### ISSUE THREAD

**Issue by danielwestendorf** [turbolinks/turbolinks-android#88]
I've been creating an Android version of my app using turbolinks-android after implementing it on the web and iOS (using turbolinks-ios). I've found HTML layout which has broken scrolling _only_ on the Android version.

When a fixed height element has scrolling content, scrolling down works fine, however, scrolling up invokes pull-to-refresh. Disabling pull-to-refresh results in no bug.

Here is an example of the bug:
![broken-scroll](https://user-images.githubusercontent.com/44478/36080701-622e4594-0f51-11e8-9a5e-f028a084e270.gif)

[Here](https://gist.github.com/danielwestendorf/92baf5013442e915e6c1533ced5cd83f) is a reproduction of the HTML which causes the bug.

It looks like this might be a bug with the pull-to-refresh feature, or maybe something with how I have my application configured? This is my first Android app so forgive any bad assumptions.

**Comment by mlepicki** [comment]
The problem seems to come from the default implementation of `RefreshLayout`, which is detecting dragging events in a way that it also consumes underlying, nested scrolls. It is possible to disable dragging detection if the view was scrolled, but currently, it is done only if the whole page has been scrolled - you can see it in line https://github.com/turbolinks/turbolinks-android/blob/98c2cd4c46e01290ee8873b944bd20b8db80da9e/turbolinks/src/main/java/com/basecamp/turbolinks/TurbolinksSession.java#L813 - in order to make it work this method should detect that we're scrolling inner div. But, apparently, WebView seems to lack such detection method. 

I'll try to find a workaround here, but it won't be an one-liner

**Comment by sobanakram** [comment]
Hi @mlepicki were you able to make it work?

**Comment by mlepicki** [comment]
Hi @sobanakram no, unfortunately. We've changed the website layout back then.
