### ISSUE TITLE
default dialogs (e.g. date/time) don't work

### ISSUE THREAD

**Issue by kassim** [turbolinks/turbolinks-android#92]
Because the WebView is instantiated using the application context, the default dialogs (e.g. date and time pickers) don't show. So you have to figure out some workaround to make your app work with date/time forms.

This should probably be added as a warning.

> Note: WebView should always be instantiated with an Activity Context. If instantiated with an Application Context, WebView will be unable to provide several features, such as JavaScript dialogs and autofill.
https://developer.android.com/reference/android/webkit/WebView.html

**Comment by fcatuhe** [comment]
Hello @kassim, did you find a workaround? I would be interested !

**Comment by lateplate** [comment]
@kassim That's definitely valid documentation but currently (and this is subject to change soon because we ran into issues with Chrome 64) we swap the application context with the current activity's context whenever a new activity is loaded. And so dialogs, such as a `<select>` or date picker should be OK. We've been using them in Basecamp without issue, so I'm curious what the issue might be. Can you share a `visit()` call you're making?

When we do eventually make the change to not swap the application context out (which Chrome 64 is going to force us to do, we're investigating now), we we for sure either provide this warning clearly or provide some backup options on how to take care of these dialogs yourself.

Thanks!

**Comment by mityakoval** [comment]
Hi! Any news on when this is going to be implemented?

**Comment by lateplate** [comment]
Hi, are you having trouble specifically with date/time? I confirmed that most web-to-native dialogs work OK (specifically dialogs) but it's possible that date/time fields might have issues.

If it is troublesome, I believe this is more a webview/Chrome interaction issue than it is anything specific to Turbolinks. One solution might be to inject your own Javascript into the webview which can listen for the proper events. There are a [handful of posts](https://www.google.com/search?q=inject+javascript+into+html+android&oq=inject+javascript+into+html+android&aqs=chrome..69i57j0.4082j1j7&sourceid=chrome&ie=UTF-8) that show you how to do that.

The Javascript you'd want to inject would look something like this. It would listen for the right type of event, and then pass it off to your own Javascript interface.

```javascript
$(document).on('click', '[type~=date]', function(event) {
    YourJavascriptInterface.showDatePicker(event.target.id)
    return false
})
```

Turbolinks gives you the ability to add Javascript interfaces into the webview via the `TurbolinksSession`...

```
turbolinksSession.addJavascriptInterface(BasecampJavascriptInterface(this.turbolinksSessionId), "YourJavascriptInterface")
```

Then in your `YourJavascriptInterface` file you'd create your own standard Android date dialog, take the values, and push them back into the webview component.

**Comment by mityakoval** [comment]
Nice! I'll give it try. Thanks!

**Comment by svantepolk** [comment]
The solution suggested by @lateplate seems to only work for the first Activity in the backstack which created an instance of a TurbolinksView.
